CREATE TABLE `stm_fld_batch` (
  `id` int NOT NULL AUTO_INCREMENT,
  `biz_name` varchar(100) DEFAULT NULL COMMENT '상호명',
  `ceo_name` varchar(100) DEFAULT NULL COMMENT '대표자',
  `biz_type` varchar(100) DEFAULT NULL COMMENT '영위업종',
  `building_division` char(2) DEFAULT NULL COMMENT '건물구분',
  `address` varchar(100) DEFAULT NULL COMMENT '주소',
  `detail_address` varchar(100) DEFAULT NULL COMMENT '상세주소',
  `area` varchar(100) DEFAULT NULL COMMENT '실사용면적',
  `biz_site_lease` varchar(100) DEFAULT NULL COMMENT '사업장임차여부',
  `ugrnd_flr_cnt` varchar(100) DEFAULT NULL COMMENT '지하층수',
  `bld_tot_lyr_num` varchar(100) DEFAULT NULL COMMENT '건물전체층수(끝층)',
  `input_bld_st` varchar(100) DEFAULT NULL COMMENT '가입층수(시작층)',
  `input_bld_ed` varchar(100) DEFAULT NULL COMMENT '가입층수(끝층)',
  `strct_cd_nm` varchar(100) DEFAULT NULL COMMENT '철근콘크리트구조',
  `roof_strc` varchar(100) DEFAULT NULL COMMENT '지붕구조',
  `otwl_strc` varchar(100) DEFAULT NULL COMMENT '외벽구조',
  `worker_num_standard_under_yn` char(2) DEFAULT NULL COMMENT '상시 근로자수 기준 미만 여부',
  `worker_num` varchar(100) DEFAULT NULL COMMENT '상시 근로자수',
  `sales_standard_under_yn` char(2) DEFAULT NULL COMMENT '매출액 기준 미만 여부',
  `sales` varchar(100) DEFAULT NULL COMMENT '매출액(백만원)',
  `biz_no` varchar(100) DEFAULT NULL COMMENT '사업자번호',
  `termsA1` char(2) DEFAULT NULL COMMENT '소비자권익에 관한사항',
  `termsA2` char(2) DEFAULT NULL COMMENT '단체규약',
  `termsA3` char(2) DEFAULT NULL COMMENT '민감정보 및 고유식별정보의 처리에 관한 사항',
  `termsA4` char(2) DEFAULT NULL COMMENT '개인(신용)정보의 사전 수집.이용에 관한 사항',
  `termsA6` char(2) DEFAULT NULL COMMENT '개인(신용)정보의 조회에 관한 사항',
  `termsA7` char(2) DEFAULT NULL COMMENT '개인(신용)정보의 제공에 관한 사항',
  `imputation_reason_confirm_yn` char(2) DEFAULT NULL COMMENT '귀책 사유 확인',
  `create_date` varchar(100) DEFAULT NULL COMMENT '생성일자',
  `termsA8` char(2) DEFAULT NULL COMMENT '마케팅이용 동의에 관한사항(선택)',
  `difStmFldJoinYn` char(2) DEFAULT NULL COMMENT '타 풍수해보험 가입 여부',
  `phoneNum` varchar(100) DEFAULT NULL COMMENT '휴대폰 번호',
  `birthDate` varchar(100) DEFAULT NULL COMMENT '생년월일',
  `sex` char(2) DEFAULT NULL COMMENT '성별',
  `jehuCd` varchar(100) DEFAULT NULL COMMENT '제휴처',
  `roadAddr` varchar(100) DEFAULT NULL COMMENT '도로명 주소'
  `bunjiAddr` varchar(100) DEFAULT NULL COMMENT '법정동 주소'
  `zipCode` varchar(100) DEFAULT NULL,
  `squareMeter` decimal(10,2) DEFAULT NULL,
  `data_processed` tinyint(1) DEFAULT 0,
  `db_processed` tinyint(1) DEFAULT 0,
  `data_skip` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 0 DEFAULT CHARSET = utf8mb3;
